import Head from 'next/head';
import styles from '../styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import React from 'react';
import BannerPopModal from './Components/BannerPopModal';
import NavScrollExample from './Components/navbar';
//import Popup from './Popup';
//import EmailConfirmation from './Components/email'
import Carousel1 from './Components/Carousel';
import Footer from './Components/footer';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Thetrendline</title>
        <meta name="description" content="Generated by Sudhir Kumar" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavScrollExample/>
      
      <BannerPopModal/>   
      <Carousel1/>
      <Footer/>

    </div>
  );
}
