import React from "react";

const EmailConfirmation = ({
  name = "Sudhir Kumar",
  confirmationLink = " ",
  otp = "123456",
  privacyPolicyLink = "https://www.youtube.com/@AgriVision4U",
  termsAndConditionsLink = "https://www.youtube.com/@AgriVision4U",
  instagramLink = "https://www.instagram.com/agrivision4u__/",
  twitterLink = "https://twitter.com/agrivision4u",
  linkedInLink = "https://www.linkedin.com/company/agrivision4u-official/",
  youtubeLink = "https://www.youtube.com/@AgriVision4U",
}) => {
  const containerStyle = {
    maxWidth: "600px",
    margin: "0 auto",
    padding: "20px",
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#f7f7f7",
  };

  const headerStyle = {
    textAlign: "center",
    padding: "20px 0",
  };

  const contentStyle = {
    backgroundColor: "#fff",
    padding: "20px",
    borderRadius: "5px",
  };

  const linkStyle = {
    color: "#007bff",
    textDecoration: "none",
  };

  const socialIconStyle = {
    display: "inline-block",
    margin: "0 10px",
    color: "#007bff",
    textDecoration: "none",
  };

  const disclaimerStyle = {
    color: "#969487",
  };

  return (
    <div style={containerStyle}>
      <div style={headerStyle}>
        <h1>
          <b>Agrivision4U</b>
        </h1>
      </div>
      <div style={contentStyle}>
        <p><b>Verify your Email</b></p>
        <p>Hello {name},<br/>
          Welcome to our platform! Please confirm your email address by clicking
          the link Here : <a style={linkStyle} href={confirmationLink}>
            Confirm Email
          </a>
        </p>
        
        <p>Your OTP (One-Time Password):<b>{otp}</b> </p>

        <p>
          If you have any questions or need assistance, please contact us at{" "}
          <a style={linkStyle} href="mailto:innovation@agrivision4u.com">
            innovation@agrivision4u.com
          </a>
        </p>
       
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <a
            style={socialIconStyle}
            href={instagramLink}
            target="_blank"
            rel="noopener noreferrer"
          >
            Instagram
          </a>
          <a
            style={socialIconStyle}
            href={twitterLink}
            target="_blank"
            rel="noopener noreferrer"
          >
            Twitter
          </a>
          <a
            style={socialIconStyle}
            href={linkedInLink}
            target="_blank"
            rel="noopener noreferrer"
          >
            LinkedIn
          </a>
          <a
            style={socialIconStyle}
            href={youtubeLink}
            target="_blank"
            rel="noopener noreferrer"
          >
            YouTube
          </a>
        </div>
        
        <p style={{            
            fontSize: "14px",
            textAlign: "center",
          }}>Keep Learning, Keep Growing!</p>
          <p style={{fontSize: "10px",display: 'flex', justifyContent: 'center' }}>
          This is an auto-generated email, please do not reply.
        </p>
      </div>
      <div>
        <p
          style={{
            fontSize: "10px",
            textAlign: "center",
          }}
        >
          Generated by Agrivision4U Pvt Ltd., 2nd Floor, Smart Seed, AICTSL
          Campus. Chartered Bus Stand Near Geeta Bhawan Square, Indore MP, PIN
          452001·
          
          Contact: +91 7510545225. © 2023, <a href="https://www.agrivision4u.com/" target="_blank">Agrivision4U</a> Pvt Ltd.
          <br />
          All rights reserved. Explore our privacy policy.
        </p>
      </div>
    </div>
  );
};

export default EmailConfirmation;
