const { User, Package, Course, OneTimePassword, OtpV3 } = require("../../../models");
const bcrypt = require("bcrypt");
const { randString, generateToken, generateOTP, sendEmailBrev } = require("../../../utils");
const transporter = require("../../../config/nodemailer");
const { sendOtp } = require("../../../config/aws_sns");
const axios = require("axios")
import React from "react";



module.exports.registerUser = async (req, res) => {
  try {
    let user = await User.findOne({ email: req.body.email }).populate(
      "courses"
    );

    if (user) {
      return res.status(400).json({
        message: "User already exists",
        success: false,
      });
    }
    let confirmationCode = randString();

    sendEmailBrev(req.body.email, "Agrivision4U Verify your Email", `
    const EmailConfirmation = ({
      privacyPolicyLink = "https://www.youtube.com/@AgriVision4U",
      termsAndConditionsLink = "https://www.youtube.com/@AgriVision4U",
      instagramLink = "https://www.instagram.com/agrivision4u__/",
      twitterLink = "https://twitter.com/agrivision4u",
      linkedInLink = "https://www.linkedin.com/company/agrivision4u-official/",
      youtubeLink = "https://www.youtube.com/@AgriVision4U",
    }) => {
      const containerStyle = {
        maxWidth: "600px",
        margin: "0 auto",
        padding: "20px",
        fontFamily: "Arial, sans-serif",
        backgroundColor: "#f7f7f7",
      };
    
      const headerStyle = {
        textAlign: "center",
        padding: "20px 0",
      };
    
      const contentStyle = {
        backgroundColor: "#fff",
        padding: "20px",
        borderRadius: "5px",
      };
    
      const linkStyle = {
        color: "#007bff",
        textDecoration: "none",
      };
    
      const socialIconStyle = {
        display: "inline-block",
        margin: "0 10px",
        color: "#007bff",
        textDecoration: "none",
      };
    
      const disclaimerStyle = {
        color: "#969487",
      };
    
      return (
        <div style={containerStyle}>
          <div style={headerStyle}>
            <h1>
              <b>Agrivision4U</b>
            </h1>
          </div>
          <div style={contentStyle}>
            <p><b>Verify your Email</b></p>
            <p>Hello${req.body.name[0]}  ${req.body.name[1]},<br/>
              Welcome to our platform! Please confirm your email address by clicking
              the link Here : <a style={linkStyle} href={confirmationLink}>
               <a href='https://www.agrivision4u.com/?confirm=${confirmationCode}'><h3> Confirm Email : </h3></a>

              </a>
            </p>
            
            <p>Your OTP (One-Time Password):<b>${confirmationCode}</b> </p>
    
            <p>
              If you have any questions or need assistance, please contact us at{" "}
              <a style={linkStyle} href="mailto:innovation@agrivision4u.com">
                innovation@agrivision4u.com
              </a>
            </p>
           
            <div style={{ display: 'flex', justifyContent: 'center' }}>
              <a
                style={socialIconStyle}
                href={instagramLink}
                target="_blank"
                rel="noopener noreferrer"
              >
                Instagram
              </a>
              <a
                style={socialIconStyle}
                href={twitterLink}
                target="_blank"
                rel="noopener noreferrer"
              >
                Twitter
              </a>
              <a
                style={socialIconStyle}
                href={linkedInLink}
                target="_blank"
                rel="noopener noreferrer"
              >
                LinkedIn
              </a>
              <a
                style={socialIconStyle}
                href={youtubeLink}
                target="_blank"
                rel="noopener noreferrer"
              >
                YouTube
              </a>
            </div>
            
            <p style={{            
                fontSize: "14px",
                textAlign: "center",
              }}>Keep Learning, Keep Growing!</p>
              <p style={{fontSize: "10px",display: 'flex', justifyContent: 'center' }}>
              This is an auto-generated email, please do not reply.
            </p>
          </div>
          <div>
            <p
              style={{
                fontSize: "10px",
                textAlign: "center",
              }}
            >
              Generated by Agrivision4U Pvt Ltd., 2nd Floor, Smart Seed, AICTSL
              Campus. Chartered Bus Stand Near Geeta Bhawan Square, Indore MP, PIN
              452001·
              
              Contact: +91 7510545225. © 2023, <a href="https://www.agrivision4u.com/" target="_blank">Agrivision4U</a> Pvt Ltd.
              <br />
              All rights reserved. Explore our privacy policy.
            </p>
          </div>
        </div>
      );
    };
    ')
    
    










    let hash = await bcrypt.hash(req.body.password, 10);

    user = new User({
      name: req.body.name,
      email: req.body.email,
      password: hash,
      randString: confirmationCode,
      contactNumber: req.body.mobileNum
    });

    await user.save();

    res.status(200).json({
      message: "Please verify your email to login",
      data: {
        user: user,
      },
      success: true,
    });
  } catch (err) {
    console.log(err);
    res.status(500).json({
      error: err.message,
      message: "something went wrong",
      success: false,
    });
  }
};